### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [lperezp/lperezp-zsh-theme#1]
**Is your feature request related to a problem? Please describe.**

I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Describe the solution you'd like**

Please add a screen shot

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by lperezp** [comment]
Hi @unixorn ! I have uploaded a preview of the theme.

Greetings!
